version: "3.8"

services:
  backend:
    build:
      context: ./RAG-Backend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    networks:
      - app-network

  frontend:
    build:
      context: ./RAG-Frontend
      dockerfile: Dockerfile

    ports:
      - "80:80"

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
