version: "3.8"

services:
  backend:
    build:
      context: https://github.com/BobbieRule/RAG-Backend.git#main
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    networks:
      - app-network

    env_file:
      - .env.backend

  frontend:
    build:
      context: https://github.com/BobbieRule/RAG-Frontend.git#main
      dockerfile: Dockerfile

    ports:
      - "80:80"

    networks:
      - app-network

    env_file:
      - .env.frontend

networks:
  app-network:
    driver: bridge
